export const PRIMARY = "#4359fc";
export const DARK_BLUE = "#0014a9";
export const TEXT_BLACK = "#333";
export const GRAY = "#999";
export const LIGHT_GRAY = "#f5f5f7";

export const styles = {
  page: {
    fontFamily: "'Pretendard', 'Noto Sans KR', sans-serif",
    minHeight: "100vh",
    background: LIGHT_GRAY,
    color: TEXT_BLACK,
  },
  main: {
    maxWidth: 1280,
    margin: "0 auto",
    padding: "28px 40px 80px",
  },
  breadcrumb: {
    display: "flex",
    gap: 6,
    alignItems: "center",
    fontSize: 12,
    marginBottom: 24,
  },
  breadcrumbItem: {
    display: "flex",
    gap: 6,
    alignItems: "center",
  },
  breadcrumbLink: { color: GRAY, cursor: "pointer" },
  breadcrumbSep: { color: "#d9d9d9" },
  breadcrumbActive: { color: PRIMARY, fontWeight: 700 },
  contentLayout: {
    display: "flex",
    gap: 24,
    alignItems: "flex-start",
  },
  sidebar: {
    width: 200,
    flexShrink: 0,
    background: "#fff",
    borderRadius: 14,
    border: "1px solid #eee",
    padding: "20px 0",
    position: "sticky",
    top: 88,
  },
  sidebarCategory: {
    fontSize: 12,
    fontWeight: 700,
    color: "#aaa",
    padding: "12px 20px 6px",
    letterSpacing: "0.2px",
  },
  sidebarItem: (isActive) => ({
    display: "block",
    width: "100%",
    textAlign: "left",
    background: isActive ? "#eef0ff" : "none",
    border: "none",
    borderLeft: isActive ? `3px solid ${PRIMARY}` : "3px solid transparent",
    padding: "9px 20px",
    fontSize: 13,
    fontWeight: isActive ? 700 : 400,
    color: isActive ? PRIMARY : TEXT_BLACK,
    cursor: "pointer",
    transition: "all 0.15s",
  }),
  contentArea: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  heroCard: {
    background: "#fff",
    border: "1px solid #eee",
    borderRadius: 16,
    padding: "28px 36px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
    overflow: "hidden",
  },
  heroBadge: (color = PRIMARY, bg = "#eef0ff", border = "#c5caff") => ({
    display: "inline-block",
    fontSize: 11,
    fontWeight: 700,
    color,
    background: bg,
    border: `1px solid ${border}`,
    borderRadius: 20,
    padding: "3px 12px",
    marginBottom: 12,
  }),
  heroTitle: {
    fontSize: 24,
    fontWeight: 700,
    color: TEXT_BLACK,
    margin: "0 0 8px",
    letterSpacing: "-0.5px",
  },
  heroSub: { fontSize: 12, color: GRAY, margin: 0 },
  heroIllust: {
    width: 80,
    height: 80,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #eef0ff 0%, #dde1ff 100%)",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  noticeBanner: {
    background: "#fffbe6",
    border: "1px solid #ffe58f",
    borderRadius: 12,
    padding: "13px 20px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 12,
    fontWeight: 500,
    color: DARK_BLUE,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: 700,
    color: "#111",
    margin: "0 0 14px",
    letterSpacing: "-0.3px",
  },
  infoCardRow: { display: "flex", gap: 14 },
  infoCard: {
    flex: 1,
    background: "#fff",
    border: "1.5px solid #eee",
    borderRadius: 12,
    padding: "16px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    cursor: "pointer",
    transition: "border-color 0.15s",
    textAlign: "left",
  },
  infoCardInner: { display: "flex", gap: 14, alignItems: "center" },
  infoCardIcon: {
    width: 38,
    height: 38,
    borderRadius: 10,
    background: "#eef0ff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  infoCardTitle: { fontSize: 14, fontWeight: 700, color: TEXT_BLACK },
  infoCardSub: { fontSize: 11, color: GRAY, marginTop: 2 },
  infoCardArrow: (active = false) => ({ fontSize: 18, color: active ? PRIMARY : "#ccc" }),
};
